version: '3'
services:
  db:
    image: postgis/postgis:9.5-3.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - db.env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'; env"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - app.env

  pgadmin:
    image: dpage/pgadmin4:6.21
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: your@email.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
    depends_on:
      - db
